FROM golang:1.18-alpine AS builder

WORKDIR /app

COPY . .

RUN go mod download

RUN go build .

FROM alpine:3.16

WORKDIR /app

COPY --from=builder /app/graphql .

EXPOSE 8080

ENTRYPOINT ["./graphql"]