FROM python:3.8.3-slim
RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY ./setup.py .
COPY ./migrationsV2.sql .
CMD ["python", "setup.py"]