CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "AspNetRoles" (
    "Id" text NOT NULL,
    "Name" character varying(256) NULL,
    "NormalizedName" character varying(256) NULL,
    "ConcurrencyStamp" text NULL,
    CONSTRAINT "PK_AspNetRoles" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetUsers" (
    "Id" text NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "UserName" character varying(256) NULL,
    "NormalizedUserName" character varying(256) NULL,
    "Email" character varying(256) NULL,
    "NormalizedEmail" character varying(256) NULL,
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text NULL,
    "SecurityStamp" text NULL,
    "ConcurrencyStamp" text NULL,
    "PhoneNumber" text NULL,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone NULL,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_AspNetUsers" PRIMARY KEY ("Id")
);

CREATE TABLE "AspNetRoleClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" text NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_AspNetRoleClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetRoleClaims_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserClaims" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" text NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_AspNetUserClaims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AspNetUserClaims_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserLogins" (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserLogins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_AspNetUserLogins_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserRoles" (
    "UserId" text NOT NULL,
    "RoleId" text NOT NULL,
    CONSTRAINT "PK_AspNetUserRoles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_AspNetUserRoles_AspNetRoles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "AspNetRoles" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_AspNetUserRoles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "AspNetUserTokens" (
    "UserId" text NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text NULL,
    CONSTRAINT "PK_AspNetUserTokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_AspNetUserTokens_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Profiles" (
    "ProfileId" text NOT NULL,
    "FirstName" text NOT NULL,
    "LastName" text NOT NULL,
    "Email" text NOT NULL,
    "Phone" text NOT NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_Profiles" PRIMARY KEY ("ProfileId"),
    CONSTRAINT "FK_Profiles_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "RefreshToken" (
    "Token" text NOT NULL,
    id text NOT NULL,
    "TokenExpire" timestamp with time zone NOT NULL,
    "TokenCreated" timestamp with time zone NOT NULL,
    "Revoked" timestamp with time zone NULL,
    "Invalidated" boolean NOT NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_RefreshToken" PRIMARY KEY ("Token"),
    CONSTRAINT "FK_RefreshToken_AspNetUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AspNetUsers" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Products" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "price"  numeric(65, 30) NOT NULL,
    "quantity" INTEGER NOT NULL,

    CONSTRAINT "Product_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "Reviews" (
    "id" UUID NOT NULL DEFAULT gen_random_uuid(),
    "productId" UUID NOT NULL,
    "profileId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT NOT NULL,
    "rating" INTEGER NOT NULL,

    CONSTRAINT "Review_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "Review_productId_fkey" FOREIGN KEY ("productId") REFERENCES "Products"("id") ON DELETE CASCADE,
    CONSTRAINT "Review_profileId_fkey" FOREIGN KEY ("profileId") REFERENCES "Profiles"("ProfileId") ON DELETE RESTRICT ON UPDATE CASCADE
);

INSERT INTO "AspNetRoles" ("Id", "ConcurrencyStamp", "Name", "NormalizedName")
VALUES ('b042b155-1a27-4ad7-826b-10452997aeac', '79d3ce86-e236-4fbc-966b-b35fb215da49', 'Admin', 'ADMIN');

CREATE INDEX "IX_AspNetRoleClaims_RoleId" ON "AspNetRoleClaims" ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON "AspNetRoles" ("NormalizedName");

CREATE INDEX "IX_AspNetUserClaims_UserId" ON "AspNetUserClaims" ("UserId");

CREATE INDEX "IX_AspNetUserLogins_UserId" ON "AspNetUserLogins" ("UserId");

CREATE INDEX "IX_AspNetUserRoles_RoleId" ON "AspNetUserRoles" ("RoleId");

CREATE INDEX "EmailIndex" ON "AspNetUsers" ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON "AspNetUsers" ("NormalizedUserName");

CREATE UNIQUE INDEX "IX_Profiles_UserId" ON "Profiles" ("UserId");

CREATE INDEX "IX_RefreshToken_UserId" ON "RefreshToken" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20221025160139_Initialize', '6.0.10');


INSERT INTO "Products" ("id", "name", "description", "price", "quantity") VALUES ('84726401-aa95-4d1e-a30d-cd7642528d6f', 'Product 1', 'Description 1', 1.00, 1);
INSERT INTO "Products" ("id", "name", "description", "price", "quantity") VALUES ('8a6425b9-4127-4856-9aa7-0b001c6cc773', 'Product 2', 'Description 2', 2.00, 2);
INSERT INTO "Products" ("id", "name", "description", "price", "quantity") VALUES ('a923516e-3363-4940-8d54-d426a9655447', 'Product 3', 'Description 3', 3.00, 3);
INSERT INTO "Products" ("id", "name", "description", "price", "quantity") VALUES ('f31e656f-5b23-4241-b7ea-2345ffe1041e', 'Product 4', 'Description 4', 4.00, 4);
INSERT INTO "Products" ("id", "name", "description", "price", "quantity") VALUES ('8b572ea7-1bd2-4a87-9922-8a161c3238b8', 'Product 5', 'Description 5', 5.00, 5);
INSERT INTO "Products" ("id", "name", "description", "price", "quantity") VALUES ('af7ffbd9-b761-492e-8bcf-fced78ab593a', 'Product 6', 'Description 6', 6.00, 6);
INSERT INTO "Products" ("id", "name", "description", "price", "quantity") VALUES ('c1526900-efe1-4830-9d18-63772453b3ad', 'Product 7', 'Description 7', 7.00, 7);
INSERT INTO "Products" ("id", "name", "description", "price", "quantity") VALUES ('7e3f1689-8af1-40ff-98bc-b9e03ca597ea', 'Product 8', 'Description 8', 8.00, 8);
INSERT INTO "Products" ("id", "name", "description", "price", "quantity") VALUES ('76f232c9-06a3-4788-8cb9-ea4876db1edb', 'Product 9', 'Description 9', 9.00, 9);
INSERT INTO "Products" ("id", "name", "description", "price", "quantity") VALUES ('89aad33c-c1e4-4605-aa2b-0b2056c138f0', 'Product 10', 'Description 10', 10.00, 10);

COMMIT;

