FROM golang:1.18-alpine AS builder

WORKDIR /app

COPY . .

RUN go mod download

RUN go build .

FROM alpine:3.16

WORKDIR /app

COPY --from=builder /app/proxy .

COPY --from=builder /app/config.yaml .

EXPOSE 4000

ENTRYPOINT ["./proxy"]